package com.enit.orderservice.application.saga;

public enum SagaStep {
    ORDER_CREATED,
    PRICING_REQUESTED,
    PRICING_COMPLETED,
    INVENTORY_REQUESTED,
    INVENTORY_RESERVED,
    CARD_VALIDATION_REQUESTED,
    CARD_VALIDATED,
    PAYMENT_REQUESTED,
    PAYMENT_PROCESSED,
    DELIVERY_REQUESTED,
    DELIVERY_CREATED,
    NOTIFICATION_SENT,
    ORDER_COMPLETED,
    COMPENSATION_STARTED,
    ORDER_FAILED
}
